source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'IronSourceDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
pod 'IronSourceSDK'
pod 'zMaticoo'
pod 'DataEyeSDK',:git => 'https://gitlab.yeahmobi.com/yeahmobile/ios-sdk.git'
  # Pods for IronSourceDemoApp

end
